### ISSUE TITLE
All prescription dates not being returned as Date object string.

### ISSUE THREAD

**Issue by andrewjyang** [Pharmachain/WebPhapp#43]
@jacobkrantz 
- prescription dates being returned as int in Pharmachain master branch
- Using route to return prescriptions by patient ID
- curl "http://localhost:5000/api/v1/prescriptions/1"

**Comment by jacobkrantz** [comment]
@andrewjyang I was unable to reproduce this issue so I decided to try from a fresh version of the WebPhapp. I cloned into the repo, went to `WebPhapp/backend`, ran `npm install`, and ran `npm run start`. In another terminal, I called `curl "http://localhost:5000/api/v1/prescriptions/1"`. Every date returned was a string. Example: `"fillDates":["Thu Jan 03 2019 16:00:00 GMT-0800 (PST)"],`. Please try re-cloning into the repository and running these steps. Make sure you commit your work before doing so. If you reproduce the issue, let me know and we will do a deeper dive.

**Comment by andrewjyang** [comment]
@jacobkrantz fixed by running npm install... my b
